### PR TITLE
Review/Rating Screens

### PR DESCRIPTION
**Pull request by evynguyen**
Users have the ability to submit a review of the club, including a title, review, and rating based on a 5 star scale

[TODO]
- fix the star rating functionality so that the page remains still when clicking on the star
- implement some action after the review has been submitted
- change the preview text and alignment of the input boxes

### CODE REVIEW

**Comment by evynguyen** [comment]
I just realized I forgot to add club title and image so that is another todo

**Comment by jsi19** [comment]
Can you add a screenshot of what this is supposed to look like? I will approve after I visually see its good to go :)

**Comment by evynguyen** [comment]
@jsi19 
screenshot!
Screen Shot

**Review by jsi19 — APPROVED** [review]
Looks really good. No Issues with other parts of app. Start looking into connecting this page to theclub profile

**Pull request merged**
